language: objective-c
osx_image: xcode9.3
cache:
  directories:
  - $HOME/Library/Caches/org.carthage.CarthageKit/dependencies
  - Carthage
before_install:
  - ./swiftmage updateTools

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - CMD="testIOSDebug"
    - CMD="testIOSRelease"
    - CMD="testMacOSDebug"
    - CMD="testMacOSRelease"
    - CMD="testTVOSDebug"
    - CMD="testTVOSRelease"
    - CMD="buildWatchOSDebug"
    - CMD="buildWatchOSRelease"

script:
  - ./swiftmage $CMD

jobs:
  include:
    - stage: Pod lib lint
      script: ./swiftmage podLint

    - stage: Deploy Github
      script: skip
      before_deploy:
        - ./swiftmage buildFramework
        - ./swiftmage archiveFramework
      deploy:
        - provider: releases
          api_key:
            secure: heGx1p/kdqW1r3rtlqwm/qFMAy+2j7NoodPtfhCgaAHUtg8rOYffZi8Hw1QSNll15PSLyQBzGbSiG8AQP9Rw02qeQd1tX7Rrob8EqqYF/mPaXP32bb81fROeOgq53xLSWSu4M0nKxL6VwUs4S2ztYR0X++zMhNrNorTaSWzwqU2dyozEpsa6zz65ukfZMwCJ1+25tQpnbt590AbbhH7y9L1AhPgJyKqaCImp9Nc4PgvhcYIm33fGEOOL3enDxe9Uoas1mKVczseT68Jc7UYWwe+2P7lhCTElHqIV7ae6+49XlnpSiPVhI3+aKHvIltWhWpLDCIzMj1SW3WRYvBFGIhYbC6kEw7pStanUiT2R7PTYOjGDqU36Gt27ZypdypbhlSRshZd3Oh3U13saH3SmPPhn+/+j12vxrUGviMg6Hxc3I76+7wozUGoN6JQ8fb0p4sNk4Qijtbp825nH9ISKSUEDRDKN2gk4pTkoiJvHzoZGF6XUpDnLAh9Psxjcg9j9oouuhBENvZPpYV/viHenjCh8xJBcJNTLFanXMSqUh2aL17rK2TsiU+TvizF/IBh12UZ2iK20xvddF20jljmmLzS2Kp53okDN/dpmqTMb/55zMXoURrJeET+2db9r4WacAZIQrg3JC96GSIytNZS7y3Qgd4KgPoouX1zVukwCeb4=
          file:
            - Nappa.framework.zip
          skip_cleanup: true
          overwrite: true
          on:
            repo: AlTavares/Nappa
            tags: true

    - stage: Deploy Cocoapods
      script: skip
      deploy:
        - provider: script
          script: ./swiftmage podPush
          skip_cleanup: true
          on:
            tags: true
