name: Nappa
options:
  bundleIdPrefix: xyz.tavares
targets:
  Nappa:
    type: framework
    platform: [iOS, tvOS, macOS, watchOS]
    deploymentTarget: "9.0"
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
      MACOSX_DEPLOYMENT_TARGET: 10.13
      WATCHOS_DEPLOYMENT_TARGET: 2.0
    sources: Sources/Nappa
    dependencies:
      - carthage: Result
    scheme:
      testTargets:
        - NappaTests_$platform
  NappaTests:
    type: bundle.unit-test
    platform: [iOS, tvOS, watchOS]
    sources: Tests/NappaTests
    dependencies:
      - target: Nappa_$platform
      - carthage: Result
      - carthage: Quick
      - carthage: Nimble
  NappaTests_macOS:
    type: bundle.unit-test
    platform: macOS
    sources: Tests/NappaTests
    dependencies:
      - target: Nappa_macOS
      - carthage: Result
      - carthage: Quick
      - carthage: Nimble
    settings:
      LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks @loader_path/../Frameworks"
